/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.SistemaEscolarDeAutomacao.Gui.Cadastro;

import com.mycompany.SistemaEscolarDeAutomacao.Dao.DAOOperacoes;
import com.mycompany.SistemaEscolarDeAutomacao.Entities.Aluno;
import com.mycompany.SistemaEscolarDeAutomacao.Gerais.PlaceHolder;
import com.mycompany.SistemaEscolarDeAutomacao.Gerais.PreencherComboBox;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author mrdaniel
 */
public class CadastroAluno extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CadastroAluno.class.getName());

    private static CadastroAluno instance;

    public static CadastroAluno getInstance() {
        if (instance == null) {
            instance = new CadastroAluno();
        }
        return instance;
    }

    public static void setInstance(CadastroAluno instance) {
        CadastroAluno.instance = instance;
    }
    
    PreencherComboBox pcb = new PreencherComboBox();

    /**
     * Creates new form CadastroAluno
     */
    public CadastroAluno() {
        initComponents();
        PlaceHolder.addPlaceHolder(nomeAluno);
        PlaceHolder.addPlaceHolder(idadeAluno);
        PlaceHolder.addPlaceHolder(cpfAluno);
        PlaceHolder.addPlaceHolder(dataNascimento);
        PlaceHolder.addPlaceHolderComboBox(salaAluno);
        PlaceHolder.addPlaceHolderComboBox(turnoAluno);
        pcb.PreencherComboBoxSalas(salaAluno);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nomeAluno = new javax.swing.JTextField();
        Cadastrar = new javax.swing.JButton();
        dataNascimento = new javax.swing.JTextField();
        cpfAluno = new javax.swing.JTextField();
        idadeAluno = new javax.swing.JTextField();
        turnoAluno = new javax.swing.JComboBox<>();
        salaAluno = new javax.swing.JComboBox<>();
        voltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Adwaita Sans", 0, 36)); // NOI18N
        jLabel1.setText("Cadastro de alunos");

        nomeAluno.setFont(new java.awt.Font("Noto Sans", 2, 13)); // NOI18N
        nomeAluno.setText("Nome");
        nomeAluno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nomeAlunoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nomeAlunoFocusLost(evt);
            }
        });

        Cadastrar.setText("Cadastrar");
        Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarActionPerformed(evt);
            }
        });

        dataNascimento.setFont(new java.awt.Font("Noto Sans", 2, 13)); // NOI18N
        dataNascimento.setText("--/--/---- (Data de nascimento)");
        dataNascimento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dataNascimentoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                dataNascimentoFocusLost(evt);
            }
        });
        dataNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataNascimentoActionPerformed(evt);
            }
        });

        cpfAluno.setFont(new java.awt.Font("Noto Sans", 2, 13)); // NOI18N
        cpfAluno.setText("CPF");
        cpfAluno.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                cpfAlunoComponentRemoved(evt);
            }
        });
        cpfAluno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cpfAlunoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cpfAlunoFocusLost(evt);
            }
        });
        cpfAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpfAlunoActionPerformed(evt);
            }
        });

        idadeAluno.setFont(new java.awt.Font("Noto Sans", 2, 13)); // NOI18N
        idadeAluno.setText("Idade");
        idadeAluno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                idadeAlunoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                idadeAlunoFocusLost(evt);
            }
        });

        turnoAluno.setFont(new java.awt.Font("Noto Sans", 2, 13)); // NOI18N
        turnoAluno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o turno", "M", "V", "N" }));
        turnoAluno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                turnoAlunoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                turnoAlunoFocusLost(evt);
            }
        });

        salaAluno.setFont(new java.awt.Font("Noto Sans", 2, 13)); // NOI18N
        salaAluno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione a sala" }));
        salaAluno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                salaAlunoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                salaAlunoFocusLost(evt);
            }
        });

        voltar.setText("Voltar");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(nomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(voltar)
                        .addGap(6, 6, 6)
                        .addComponent(Cadastrar))
                    .addComponent(dataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpfAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idadeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(turnoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salaAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(nomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idadeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cpfAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(turnoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(salaAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cadastrar)
                    .addComponent(voltar))
                .addGap(25, 25, 25))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nomeAlunoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomeAlunoFocusGained
        // TODO add your handling code here:
        if (nomeAluno.getText().equals("Nome")) {
            nomeAluno.setText(null);
            nomeAluno.requestFocus();
            PlaceHolder.removePlaceHolder(nomeAluno);
        }
    }//GEN-LAST:event_nomeAlunoFocusGained

    private void nomeAlunoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomeAlunoFocusLost
        // TODO add your handling code here:
        if (nomeAluno.getText().isEmpty()) {
            nomeAluno.setText("Nome");
            PlaceHolder.addPlaceHolder(nomeAluno);
        }
    }//GEN-LAST:event_nomeAlunoFocusLost

    private void CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarActionPerformed
        // TODO add your handling code here:
        String nome = nomeAluno.getText();
        int idade = Integer.parseInt(idadeAluno.getText());
        String cpf = cpfAluno.getText();

        LocalDate dataCad = LocalDate.now();
        LocalTime hora = LocalTime.now();

        DateTimeFormatter formatadorData = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        LocalDate dataNas = LocalDate.parse(dataNascimento.getText(), formatadorData);
        
        Aluno aluno = new Aluno();
        aluno.setNome(nome);
        aluno.setIdade(idade);
        aluno.setCpf(cpf);
        aluno.setDataCadastro(dataCad);
        aluno.setHoraCadastro(hora);
        aluno.setDataNascimento(dataNas);
        
        DAOOperacoes dao = new DAOOperacoes();
        dao.cadastrarJPA(aluno);
        
        /*

        try {
            if (!nome.isEmpty() && !permissao.equalsIgnoreCase("selecione") && (!data.toString().isEmpty() || data.toString().matches("(0[1-9]|[12][0-9]|3[01])/(0[1-9]|1[012])/(19|20)[0-9]{2}")) && (!hora.toString().isEmpty() || !hora.toString().matches("\n"
                    + "    (\"(0[1-9]|[1][0-9]|[2][0-3]):(0[1-9]|[12345][0-9]):(0[1-9]|[12345][0-9])")) && !login.isEmpty() && !senha.isEmpty()) {
                User u = new User(nome, permissao, email, telefone, data, hora, login, senha, log);
                UserDAO ud = new UserDAO();
                ud.cadastrarJPA(u);
                JOptionPane.showMessageDialog(null, "Dados cadastrados com sucesso.");
                nomeAluno.setText("");
                idade.setSelectedIndex(0);
                cpfAluno.setText("");
                dataNascimento.setText("");
                dataCadastro.setText("");
                horaCadastro.setText("");
                loginUsuario.setText("");
                senhaUsuario.setText("");

            } else {
                JOptionPane.showMessageDialog(null, "Ocorreu um erro, verifique os campos e tente novamente!");
            }
        } catch (Exception e) {
            System.out.println("Ocorreu um erro, preencha todos os campos e tente novamente!");
            System.out.println(e);
        }  */
    }//GEN-LAST:event_CadastrarActionPerformed

    private void dataNascimentoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dataNascimentoFocusGained
        // TODO add your handling code here:
        if (dataNascimento.getText().equals("--/--/---- (Data de nascimento)")) {
            dataNascimento.setText(null);
            dataNascimento.requestFocus();
            PlaceHolder.removePlaceHolder(dataNascimento);
        }
    }//GEN-LAST:event_dataNascimentoFocusGained

    private void dataNascimentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dataNascimentoFocusLost
        // TODO add your handling code here:
        if (dataNascimento.getText().isEmpty()) {
            dataNascimento.setText("--/--/---- (Data de nascimento)");
            PlaceHolder.addPlaceHolder(dataNascimento);
        }
    }//GEN-LAST:event_dataNascimentoFocusLost

    private void dataNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataNascimentoActionPerformed

    private void cpfAlunoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cpfAlunoFocusGained
        // TODO add your handling code here:
        if (cpfAluno.getText().equals("CPF")) {
            cpfAluno.setText(null);
            cpfAluno.requestFocus();
            PlaceHolder.removePlaceHolder(cpfAluno);
        }
    }//GEN-LAST:event_cpfAlunoFocusGained

    private void cpfAlunoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cpfAlunoFocusLost
        // TODO add your handling code here:
        if (cpfAluno.getText().isEmpty()) {
            cpfAluno.setText("CPF");
            PlaceHolder.addPlaceHolder(cpfAluno);
        }
    }//GEN-LAST:event_cpfAlunoFocusLost

    private void cpfAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpfAlunoActionPerformed

    private void cpfAlunoComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_cpfAlunoComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_cpfAlunoComponentRemoved

    private void idadeAlunoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idadeAlunoFocusGained
        // TODO add your handling code here:
        if (idadeAluno.getText().equals("Idade")) {
            idadeAluno.setText(null);
            idadeAluno.requestFocus();
            PlaceHolder.removePlaceHolder(idadeAluno);
        }
    }//GEN-LAST:event_idadeAlunoFocusGained

    private void idadeAlunoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idadeAlunoFocusLost
        // TODO add your handling code here:
        if (idadeAluno.getText().isEmpty()) {
            idadeAluno.setText("Idade");
            PlaceHolder.addPlaceHolder(idadeAluno);
        }
    }//GEN-LAST:event_idadeAlunoFocusLost

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        // TODO add your handling code here:
        dispose();
        CadastroAluno.setInstance(null);
        Cadastros.getInstance().setVisible(true);
    }//GEN-LAST:event_voltarActionPerformed

    private void salaAlunoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_salaAlunoFocusGained
        // TODO add your handling code here:
        if (salaAluno.getSelectedItem().toString().equals("Selecione a sala")) {
            salaAluno.requestFocus();
            PlaceHolder.removePlaceHolderComboBox(salaAluno);
        }
    }//GEN-LAST:event_salaAlunoFocusGained

    private void salaAlunoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_salaAlunoFocusLost
        // TODO add your handling code here:
        if (salaAluno.getSelectedItem().toString().equals("Selecione a sala")) {
            PlaceHolder.addPlaceHolderComboBox(salaAluno);
        }
    }//GEN-LAST:event_salaAlunoFocusLost

    private void turnoAlunoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_turnoAlunoFocusLost
        // TODO add your handling code here:
        if (turnoAluno.getSelectedItem().toString().equals("Selecione o turno")) {
            PlaceHolder.addPlaceHolderComboBox(turnoAluno);
        }
    }//GEN-LAST:event_turnoAlunoFocusLost

    private void turnoAlunoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_turnoAlunoFocusGained
        // TODO add your handling code here:
        if (turnoAluno.getSelectedItem().toString().equals("Selecione o turno")) {
            turnoAluno.requestFocus();
            PlaceHolder.removePlaceHolderComboBox(turnoAluno);
        }
    }//GEN-LAST:event_turnoAlunoFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CadastroAluno().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cadastrar;
    private javax.swing.JTextField cpfAluno;
    private javax.swing.JTextField dataNascimento;
    private javax.swing.JTextField idadeAluno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField nomeAluno;
    private javax.swing.JComboBox<String> salaAluno;
    private javax.swing.JComboBox<String> turnoAluno;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
