/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.SistemaEscolarDeAutomacao.Gui.Cadastro;

import com.mycompany.SistemaEscolarDeAutomacao.Dao.DAOOperacoes;
import com.mycompany.SistemaEscolarDeAutomacao.Entities.Horario;
import com.mycompany.SistemaEscolarDeAutomacao.Entities.Materia;
import com.mycompany.SistemaEscolarDeAutomacao.Entities.Professor;
import com.mycompany.SistemaEscolarDeAutomacao.Entities.User;
import com.mycompany.SistemaEscolarDeAutomacao.Gerais.PlaceHolder;
import com.mycompany.SistemaEscolarDeAutomacao.Gerais.PreencherComboBox;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author mrdaniel
 */
public class CadastroProfs extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CadastroProfs.class.getName());

    PreencherComboBox pcb = new PreencherComboBox();
    DAOOperacoes dao = new DAOOperacoes();

    private static CadastroProfs instance;

    public static CadastroProfs getInstance() {
        if (instance == null) {
            instance = new CadastroProfs();
        }
        return instance;
    }

    public static void setInstance(CadastroProfs instance) {
        CadastroProfs.instance = instance;
    }

    /**
     * Creates new form CadastroProfs
     */
    public CadastroProfs() {
        initComponents();
        PlaceHolder.addPlaceHolder(nomeProfessor);
        PlaceHolder.addPlaceHolder(idadeProfessor);
        PlaceHolder.addPlaceHolder(cpfProfessor);
        PlaceHolder.addPlaceHolder(dataNascimento);
        PlaceHolder.addPlaceHolder(urlCurriculo);
        PlaceHolder.addPlaceHolder(salarioProfessor);
        PlaceHolder.addPlaceHolder(formacaoProfessor);
        PlaceHolder.addPlaceHolderComboBox(salaHorario);
        PlaceHolder.addPlaceHolderComboBox(materiaProfessor);
        PlaceHolder.addPlaceHolderComboBox(usuarioProfessor);
        PlaceHolder.addPlaceHolderComboBox(horarioProfessor);

        pcb.PreencherComboBoxMaterias(materiaProfessor);
        pcb.PreencherComboBoxSalas(salaHorario);
        pcb.PreencherComboUsuarios(usuarioProfessor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idadeProfessor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        nomeProfessor = new javax.swing.JTextField();
        voltar = new javax.swing.JButton();
        Cadastrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        salaHorario = new javax.swing.JComboBox<>();
        Cadastrar1 = new javax.swing.JButton();
        Cadastrar2 = new javax.swing.JButton();
        materiaProfessor = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        usuarioProfessor = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        horarioProfessor = new javax.swing.JComboBox<>();
        cpfProfessor = new javax.swing.JTextField();
        dataNascimento = new javax.swing.JTextField();
        urlCurriculo = new javax.swing.JTextField();
        formacaoProfessor = new javax.swing.JTextField();
        salarioProfessor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        idadeProfessor.setFont(new java.awt.Font("Noto Sans", 2, 13)); // NOI18N
        idadeProfessor.setText("Idade");
        idadeProfessor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                idadeProfessorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                idadeProfessorFocusLost(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Adwaita Sans", 0, 36)); // NOI18N
        jLabel1.setText("Cadastro de professores");

        nomeProfessor.setFont(new java.awt.Font("Noto Sans", 2, 13)); // NOI18N
        nomeProfessor.setText("Nome");
        nomeProfessor.setNextFocusableComponent(idadeProfessor);
        nomeProfessor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nomeProfessorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nomeProfessorFocusLost(evt);
            }
        });

        voltar.setText("Voltar");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });

        Cadastrar.setText("Cadastrar");
        Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Adwaita Sans", 0, 18)); // NOI18N
        jLabel2.setText("Selecionar horário");

        jLabel3.setFont(new java.awt.Font("Adwaita Sans", 0, 18)); // NOI18N
        jLabel3.setText("Dados pessoais");

        jLabel4.setFont(new java.awt.Font("Adwaita Sans", 0, 18)); // NOI18N
        jLabel4.setText("Adicionar matéria");

        salaHorario.setFont(new java.awt.Font("Noto Sans", 2, 13)); // NOI18N
        salaHorario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione a sala" }));
        salaHorario.setNextFocusableComponent(horarioProfessor);
        salaHorario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                salaHorarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                salaHorarioFocusLost(evt);
            }
        });
        salaHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salaHorarioActionPerformed(evt);
            }
        });

        Cadastrar1.setText("Confirmar horário");
        Cadastrar1.setEnabled(false);
        Cadastrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cadastrar1ActionPerformed(evt);
            }
        });

        Cadastrar2.setText("Confirmar matéria");
        Cadastrar2.setEnabled(false);
        Cadastrar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cadastrar2ActionPerformed(evt);
            }
        });

        materiaProfessor.setFont(new java.awt.Font("Noto Sans", 2, 13)); // NOI18N
        materiaProfessor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione a matéria" }));
        materiaProfessor.setNextFocusableComponent(salaHorario);
        materiaProfessor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                materiaProfessorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                materiaProfessorFocusLost(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Adwaita Sans", 0, 18)); // NOI18N
        jLabel5.setText("Selecionar o usuário");

        usuarioProfessor.setFont(new java.awt.Font("Noto Sans", 2, 13)); // NOI18N
        usuarioProfessor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o usuário correspondente" }));
        usuarioProfessor.setNextFocusableComponent(voltar);
        usuarioProfessor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usuarioProfessorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usuarioProfessorFocusLost(evt);
            }
        });
        usuarioProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioProfessorActionPerformed(evt);
            }
        });

        jButton1.setText("Confirmar usuário");
        jButton1.setEnabled(false);

        horarioProfessor.setFont(new java.awt.Font("Noto Sans", 2, 13)); // NOI18N
        horarioProfessor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o horário" }));
        horarioProfessor.setNextFocusableComponent(usuarioProfessor);
        horarioProfessor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                horarioProfessorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                horarioProfessorFocusLost(evt);
            }
        });

        cpfProfessor.setFont(new java.awt.Font("Noto Sans", 2, 13)); // NOI18N
        cpfProfessor.setText("CPF");
        cpfProfessor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cpfProfessorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cpfProfessorFocusLost(evt);
            }
        });

        dataNascimento.setFont(new java.awt.Font("Noto Sans", 2, 13)); // NOI18N
        dataNascimento.setText("--/--/---- (Data de nascimento)");
        dataNascimento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dataNascimentoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                dataNascimentoFocusLost(evt);
            }
        });

        urlCurriculo.setFont(new java.awt.Font("Noto Sans", 2, 13)); // NOI18N
        urlCurriculo.setText("URL do currículo");
        urlCurriculo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                urlCurriculoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                urlCurriculoFocusLost(evt);
            }
        });

        formacaoProfessor.setFont(new java.awt.Font("Noto Sans", 2, 13)); // NOI18N
        formacaoProfessor.setText("Formação");
        formacaoProfessor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formacaoProfessorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                formacaoProfessorFocusLost(evt);
            }
        });

        salarioProfessor.setFont(new java.awt.Font("Noto Sans", 2, 13)); // NOI18N
        salarioProfessor.setText("Salário");
        salarioProfessor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                salarioProfessorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                salarioProfessorFocusLost(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel4)
                    .addComponent(materiaProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(usuarioProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(salaHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(horarioProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(idadeProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(nomeProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(voltar)
                        .addGap(6, 6, 6)
                        .addComponent(Cadastrar)
                        .addGap(6, 6, 6)
                        .addComponent(Cadastrar2)
                        .addGap(6, 6, 6)
                        .addComponent(Cadastrar1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(cpfProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(urlCurriculo, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(formacaoProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salarioProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idadeProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cpfProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(urlCurriculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formacaoProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(salarioProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(materiaProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salaHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(horarioProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jLabel5)
                .addGap(6, 6, 6)
                .addComponent(usuarioProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cadastrar)
                    .addComponent(voltar)
                    .addComponent(Cadastrar1)
                    .addComponent(Cadastrar2)
                    .addComponent(jButton1))
                .addGap(31, 31, 31))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void idadeProfessorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idadeProfessorFocusGained
        // TODO add your handling code here:
        if (idadeProfessor.getText().equals("Idade")) {
            idadeProfessor.setText(null);
            idadeProfessor.requestFocus();
            PlaceHolder.removePlaceHolder(idadeProfessor);
        }
    }//GEN-LAST:event_idadeProfessorFocusGained

    private void idadeProfessorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idadeProfessorFocusLost
        // TODO add your handling code here:
        if (idadeProfessor.getText().isEmpty()) {
            idadeProfessor.setText("Idade");
            PlaceHolder.addPlaceHolder(idadeProfessor);
        }
    }//GEN-LAST:event_idadeProfessorFocusLost

    private void nomeProfessorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomeProfessorFocusGained
        // TODO add your handling code here:
        if (nomeProfessor.getText().equals("Nome")) {
            nomeProfessor.setText(null);
            nomeProfessor.requestFocus();
            PlaceHolder.removePlaceHolder(nomeProfessor);
        }
    }//GEN-LAST:event_nomeProfessorFocusGained

    private void nomeProfessorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomeProfessorFocusLost
        // TODO add your handling code here:
        if (nomeProfessor.getText().isEmpty()) {
            nomeProfessor.setText("Nome");
            PlaceHolder.addPlaceHolder(nomeProfessor);
        }
    }//GEN-LAST:event_nomeProfessorFocusLost

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        // TODO add your handling code here:
        dispose();
        DAOOperacoes.closeMan();
        CadastroProfs.setInstance(null);
        Cadastros.getInstance().setVisible(true);
    }//GEN-LAST:event_voltarActionPerformed

    private void CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarActionPerformed
        // TODO add your handling code here:
        String nome = nomeProfessor.getText();
        int idade = Integer.parseInt(idadeProfessor.getText());
        String cpf = cpfProfessor.getText();

        DateTimeFormatter formatadorData = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        LocalDate data = LocalDate.parse(dataNascimento.getText(), formatadorData);

        LocalDate dataCad = LocalDate.now();
        LocalTime hora = LocalTime.now();

        String url = urlCurriculo.getText();
        String formacao = formacaoProfessor.getText();
        Double salario = Double.parseDouble(salarioProfessor.getText());

        List<Materia> listaMaterias = new ArrayList<>();
        listaMaterias.add(dao.buscarMateriasNome(materiaProfessor.getSelectedItem().toString()));
        List<Horario> listaHorarios = new ArrayList<>();
        listaHorarios.add(dao.buscarHorarioID(Integer.parseInt(horarioProfessor.getSelectedItem().toString())));
        User u = dao.buscarUsuarioNome(usuarioProfessor.getSelectedItem().toString());

        boolean camposPreenchidos = !nome.equals("Nome") && !idadeProfessor.getText().equals("Idade") && !cpf.equals("CPF") && !dataNascimento.getText().equals("") && !url.isEmpty() && !formacao.isEmpty() && !salarioProfessor.getText().isEmpty();
        boolean comboBoxesSelecionadas = !materiaProfessor.getSelectedItem().toString().equals("Selecione a matéria") && !salaHorario.getSelectedItem().toString().equals("Selecione a sala") && !horarioProfessor.getSelectedItem().toString().equals("Selecione o horário") && !usuarioProfessor.getSelectedItem().toString().equals("Selecione o usuário correspodente");

        try {
            if (!camposPreenchidos) {
                JOptionPane.showMessageDialog(null, "Todos os campos de dados pessoais devem estar preenchidos.");
            }

            if (!comboBoxesSelecionadas) {
                JOptionPane.showMessageDialog(null, "Todas as combo boxes devem estar com seleções válidas para que o cadastro ocorra.");
            }

            if (camposPreenchidos && comboBoxesSelecionadas) {
                Professor p = new Professor(nome, idade, cpf, url, listaMaterias, listaHorarios, salario, formacao, data, dataCad, hora, u);
                dao.cadastrarJPA(p);
                JOptionPane.showMessageDialog(null, "Cadastro bem sucedido");
                nomeProfessor.setText("Nome");
                PlaceHolder.addPlaceHolder(nomeProfessor);
                idadeProfessor.setText("Idade");
                PlaceHolder.addPlaceHolder(idadeProfessor);
                cpfProfessor.setText("CPF");
                PlaceHolder.addPlaceHolder(cpfProfessor);
                dataNascimento.setText("--/--/---- (Data de nascimento)");
                PlaceHolder.addPlaceHolder(dataNascimento);
                urlCurriculo.setText("URL do currículo");
                PlaceHolder.addPlaceHolder(urlCurriculo);
                salarioProfessor.setText("Salário");
                PlaceHolder.addPlaceHolder(salarioProfessor);
                formacaoProfessor.setText("Formação");
                PlaceHolder.addPlaceHolder(formacaoProfessor);
                salaHorario.setSelectedIndex(0);
                PlaceHolder.addPlaceHolderComboBox(salaHorario);
                materiaProfessor.setSelectedIndex(0);
                PlaceHolder.addPlaceHolderComboBox(materiaProfessor);
                usuarioProfessor.setSelectedIndex(0);
                PlaceHolder.addPlaceHolderComboBox(usuarioProfessor);
                horarioProfessor.setSelectedIndex(0);
                PlaceHolder.addPlaceHolderComboBox(horarioProfessor);
            }
        } catch (Exception e) {
            System.out.println("Ocorreu um erro, preencha todos os campos e tente novamente!");
            System.out.println(e.getMessage());
        }
        DAOOperacoes.closeMan();
    }//GEN-LAST:event_CadastrarActionPerformed

    private void Cadastrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cadastrar1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_Cadastrar1ActionPerformed

    private void Cadastrar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cadastrar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cadastrar2ActionPerformed

    private void usuarioProfessorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usuarioProfessorFocusGained
        // TODO add your handling code here:
        if (usuarioProfessor.getSelectedItem().toString().equals("Selecione o usuário correspondente")) {
            usuarioProfessor.requestFocus();
            PlaceHolder.removePlaceHolderComboBox(usuarioProfessor);
        }
    }//GEN-LAST:event_usuarioProfessorFocusGained

    private void usuarioProfessorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usuarioProfessorFocusLost
        // TODO add your handling code here:
        if (usuarioProfessor.getSelectedItem().toString().equals("Selecione o usuário correspondente")) {
            PlaceHolder.addPlaceHolderComboBox(usuarioProfessor);
        }
    }//GEN-LAST:event_usuarioProfessorFocusLost

    private void materiaProfessorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_materiaProfessorFocusLost
        // TODO add your handling code here:
        if (materiaProfessor.getSelectedItem().toString().equals("Selecione a matéria")) {
            PlaceHolder.addPlaceHolderComboBox(materiaProfessor);
        }
    }//GEN-LAST:event_materiaProfessorFocusLost

    private void materiaProfessorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_materiaProfessorFocusGained
        // TODO add your handling code here:
        if (materiaProfessor.getSelectedItem().toString().equals("Selecione a matéria")) {
            materiaProfessor.requestFocus();
            PlaceHolder.removePlaceHolderComboBox(materiaProfessor);
        }
    }//GEN-LAST:event_materiaProfessorFocusGained

    private void salaHorarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_salaHorarioFocusLost
        // TODO add your handling code here:
        if (salaHorario.getSelectedItem().toString().equals("Selecione a sala")) {
            PlaceHolder.addPlaceHolderComboBox(salaHorario);
        }
    }//GEN-LAST:event_salaHorarioFocusLost

    private void salaHorarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_salaHorarioFocusGained
        // TODO add your handling code here:
        if (salaHorario.getSelectedItem().toString().equals("Selecione a sala")) {
            salaHorario.requestFocus();
            PlaceHolder.removePlaceHolderComboBox(salaHorario);
        }
    }//GEN-LAST:event_salaHorarioFocusGained

    private void horarioProfessorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_horarioProfessorFocusGained
        // TODO add your handling code here:
        if (horarioProfessor.getSelectedItem().toString().equals("Selecione o horário")) {
            horarioProfessor.requestFocus();
            PlaceHolder.removePlaceHolderComboBox(horarioProfessor);
        }
    }//GEN-LAST:event_horarioProfessorFocusGained

    private void horarioProfessorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_horarioProfessorFocusLost
        // TODO add your handling code here:
        if (horarioProfessor.getSelectedItem().toString().equals("Selecione o horário")) {
            PlaceHolder.addPlaceHolderComboBox(horarioProfessor);
        }
    }//GEN-LAST:event_horarioProfessorFocusLost

    private void salaHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salaHorarioActionPerformed
        // TODO add your handling code here:
        pcb.EsvaziarComboBoxes(horarioProfessor);
        pcb.PreencherComboBoxHorarios(salaHorario.getSelectedItem().toString(), horarioProfessor);

    }//GEN-LAST:event_salaHorarioActionPerformed

    private void usuarioProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioProfessorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioProfessorActionPerformed

    private void cpfProfessorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cpfProfessorFocusGained
        // TODO add your handling code here:
        if (cpfProfessor.getText().equals("CPF")) {
            cpfProfessor.setText(null);
            cpfProfessor.requestFocus();
            PlaceHolder.removePlaceHolder(cpfProfessor);
        }
    }//GEN-LAST:event_cpfProfessorFocusGained

    private void cpfProfessorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cpfProfessorFocusLost
        // TODO add your handling code here:
        if (cpfProfessor.getText().isEmpty()) {
            cpfProfessor.setText("CPF");
            PlaceHolder.addPlaceHolder(cpfProfessor);
        }
    }//GEN-LAST:event_cpfProfessorFocusLost

    private void dataNascimentoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dataNascimentoFocusGained
        // TODO add your handling code here:
        if (dataNascimento.getText().equals("--/--/---- (Data de nascimento)")) {
            dataNascimento.setText(null);
            dataNascimento.requestFocus();
            PlaceHolder.removePlaceHolder(dataNascimento);
        }
    }//GEN-LAST:event_dataNascimentoFocusGained

    private void dataNascimentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dataNascimentoFocusLost
        // TODO add your handling code here:
        if (dataNascimento.getText().isEmpty()) {
            dataNascimento.setText("--/--/---- (Data de nascimento)");
            PlaceHolder.addPlaceHolder(dataNascimento);
        }
    }//GEN-LAST:event_dataNascimentoFocusLost

    private void urlCurriculoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_urlCurriculoFocusGained
        // TODO add your handling code here:
        if (urlCurriculo.getText().equals("URL do currículo")) {
            urlCurriculo.setText(null);
            urlCurriculo.requestFocus();
            PlaceHolder.removePlaceHolder(urlCurriculo);
        }
    }//GEN-LAST:event_urlCurriculoFocusGained

    private void urlCurriculoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_urlCurriculoFocusLost
        // TODO add your handling code here:
        if (urlCurriculo.getText().isEmpty()) {
            urlCurriculo.setText("URL do currículo");
            PlaceHolder.addPlaceHolder(urlCurriculo);
        }
    }//GEN-LAST:event_urlCurriculoFocusLost

    private void formacaoProfessorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formacaoProfessorFocusGained
        // TODO add your handling code here:
        if (formacaoProfessor.getText().equals("Formação")) {
            formacaoProfessor.setText(null);
            formacaoProfessor.requestFocus();
            PlaceHolder.removePlaceHolder(formacaoProfessor);
        }
    }//GEN-LAST:event_formacaoProfessorFocusGained

    private void formacaoProfessorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formacaoProfessorFocusLost
        // TODO add your handling code here:
        if (formacaoProfessor.getText().isEmpty()) {
            formacaoProfessor.setText("Formação");
            PlaceHolder.addPlaceHolder(formacaoProfessor);
        }
    }//GEN-LAST:event_formacaoProfessorFocusLost

    private void salarioProfessorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_salarioProfessorFocusGained
        // TODO add your handling code here:
        if (salarioProfessor.getText().equals("Salário")) {
            salarioProfessor.setText(null);
            salarioProfessor.requestFocus();
            PlaceHolder.removePlaceHolder(salarioProfessor);
        }
    }//GEN-LAST:event_salarioProfessorFocusGained

    private void salarioProfessorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_salarioProfessorFocusLost
        // TODO add your handling code here:
        if (salarioProfessor.getText().isEmpty()) {
            salarioProfessor.setText("Salário");
            PlaceHolder.addPlaceHolder(salarioProfessor);
        }
    }//GEN-LAST:event_salarioProfessorFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CadastroProfs().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cadastrar;
    private javax.swing.JButton Cadastrar1;
    private javax.swing.JButton Cadastrar2;
    private javax.swing.JTextField cpfProfessor;
    private javax.swing.JTextField dataNascimento;
    private javax.swing.JTextField formacaoProfessor;
    private javax.swing.JComboBox<String> horarioProfessor;
    private javax.swing.JTextField idadeProfessor;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JComboBox<String> materiaProfessor;
    private javax.swing.JTextField nomeProfessor;
    private javax.swing.JComboBox<String> salaHorario;
    private javax.swing.JTextField salarioProfessor;
    private javax.swing.JTextField urlCurriculo;
    private javax.swing.JComboBox<String> usuarioProfessor;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
