/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.SistemaEscolarDeAutomacao.Gui.Cadastro;

import com.mycompany.SistemaEscolarDeAutomacao.Dao.DAOOperacoes;
import com.mycompany.SistemaEscolarDeAutomacao.Entities.User;
import com.mycompany.SistemaEscolarDeAutomacao.Gerais.PlaceHolder;
import java.time.LocalDate;
import java.time.LocalTime;
import javax.swing.JOptionPane;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JFrame;
import java.awt.Dimension;

/**
 *
 * @author daniel
 */
public class CadastroUser extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CadastroUser.class.getName());

    private static CadastroUser instance;

    public static CadastroUser getInstance() {
        if (instance == null) {
            instance = new CadastroUser();
        }
        return instance;
    }

    public static void setInstance(CadastroUser instance) {
        CadastroUser.instance = instance;
    }

    /**
     * Creates new form CadastroUser
     */
    public CadastroUser() {
        initComponents();
        PlaceHolder.addPlaceHolder(nomeUsuario);
        PlaceHolder.addPlaceHolder(emailUsuario);
        PlaceHolder.addPlaceHolder(telefoneUsuario);
        PlaceHolder.addPlaceHolder(loginUsuario);
        PlaceHolder.addPlaceHolder(senhaUsuario);
        PlaceHolder.addPlaceHolderComboBox(comboPermissoes);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nomeUsuario = new javax.swing.JTextField();
        comboPermissoes = new javax.swing.JComboBox<>();
        loginUsuario = new javax.swing.JTextField();
        voltar = new javax.swing.JButton();
        senhaUsuario = new javax.swing.JPasswordField();
        telefoneUsuario = new javax.swing.JTextField();
        emailUsuario = new javax.swing.JTextField();
        Cadastrar = new javax.swing.JButton();
        visualizacao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Adwaita Sans", 0, 36)); // NOI18N
        jLabel1.setText("Cadastro de usuários");

        nomeUsuario.setFont(new java.awt.Font("Noto Sans", 2, 13)); // NOI18N
        nomeUsuario.setText("Nome");
        nomeUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nomeUsuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nomeUsuarioFocusLost(evt);
            }
        });

        comboPermissoes.setFont(new java.awt.Font("Noto Sans", 2, 13)); // NOI18N
        comboPermissoes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione a permissão", "Diretor", "Secretário", "Professor" }));
        comboPermissoes.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                comboPermissoesFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                comboPermissoesFocusLost(evt);
            }
        });
        comboPermissoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboPermissoesActionPerformed(evt);
            }
        });

        loginUsuario.setFont(new java.awt.Font("Noto Sans", 2, 13)); // NOI18N
        loginUsuario.setText("Login");
        loginUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                loginUsuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                loginUsuarioFocusLost(evt);
            }
        });

        voltar.setText("Voltar");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });

        senhaUsuario.setText("Senha");
        senhaUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                senhaUsuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                senhaUsuarioFocusLost(evt);
            }
        });
        senhaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaUsuarioActionPerformed(evt);
            }
        });

        telefoneUsuario.setFont(new java.awt.Font("Noto Sans", 2, 13)); // NOI18N
        telefoneUsuario.setText("Telefone (Exemplo: (27)981026479)");
        telefoneUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                telefoneUsuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                telefoneUsuarioFocusLost(evt);
            }
        });
        telefoneUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefoneUsuarioActionPerformed(evt);
            }
        });

        emailUsuario.setFont(new java.awt.Font("Noto Sans", 2, 13)); // NOI18N
        emailUsuario.setText("Email (nome@exemplo.dominio)");
        emailUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailUsuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailUsuarioFocusLost(evt);
            }
        });
        emailUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailUsuarioActionPerformed(evt);
            }
        });

        Cadastrar.setText("Cadastrar");
        Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarActionPerformed(evt);
            }
        });

        visualizacao.setText("👁");
        visualizacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visualizacaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(comboPermissoes, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(senhaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telefoneUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(visualizacao)
                        .addGap(6, 6, 6)
                        .addComponent(voltar)
                        .addGap(6, 6, 6)
                        .addComponent(Cadastrar))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(nomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(comboPermissoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(emailUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(telefoneUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(loginUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(senhaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(visualizacao)
                    .addComponent(voltar)
                    .addComponent(Cadastrar))
                .addGap(25, 25, 25))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void comboPermissoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboPermissoesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboPermissoesActionPerformed

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        // TODO add your handling code here:
        dispose();
        DAOOperacoes.closeMan();
        CadastroUser.setInstance(null);
        Cadastros.getInstance().setVisible(true);
    }//GEN-LAST:event_voltarActionPerformed

    private void telefoneUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefoneUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefoneUsuarioActionPerformed

    private void emailUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailUsuarioActionPerformed

    private void nomeUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomeUsuarioFocusGained
        // TODO add your handling code here:
        if (nomeUsuario.getText().equals("Nome")) {
            nomeUsuario.setText(null);
            nomeUsuario.requestFocus();
            PlaceHolder.removePlaceHolder(nomeUsuario);
        }
    }//GEN-LAST:event_nomeUsuarioFocusGained

    private void nomeUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomeUsuarioFocusLost
        // TODO add your handling code here:
        if (nomeUsuario.getText().isEmpty()) {
            nomeUsuario.setText("Nome");
            PlaceHolder.addPlaceHolder(nomeUsuario);
        }
    }//GEN-LAST:event_nomeUsuarioFocusLost

    private void emailUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailUsuarioFocusGained
        // TODO add your handling code here:
        if (emailUsuario.getText().equals("Email (nome@exemplo.dominio)")) {
            emailUsuario.setText(null);
            emailUsuario.requestFocus();
            PlaceHolder.removePlaceHolder(emailUsuario);
        }
    }//GEN-LAST:event_emailUsuarioFocusGained

    private void emailUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailUsuarioFocusLost
        // TODO add your handling code here:
        if (emailUsuario.getText().isEmpty()) {
            emailUsuario.setText("Email (nome@exemplo.dominio)");
            PlaceHolder.addPlaceHolder(emailUsuario);
        }
    }//GEN-LAST:event_emailUsuarioFocusLost

    private void telefoneUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_telefoneUsuarioFocusGained
        // TODO add your handling code here:
        if (telefoneUsuario.getText().equals("Telefone (Exemplo: (27)981026479)")) {
            telefoneUsuario.setText(null);
            telefoneUsuario.requestFocus();
            PlaceHolder.removePlaceHolder(telefoneUsuario);
        }
    }//GEN-LAST:event_telefoneUsuarioFocusGained

    private void telefoneUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_telefoneUsuarioFocusLost
        // TODO add your handling code here:
        if (telefoneUsuario.getText().isEmpty()) {
            telefoneUsuario.setText("Telefone (Exemplo: (27)981026479)");
            PlaceHolder.addPlaceHolder(telefoneUsuario);
        }
    }//GEN-LAST:event_telefoneUsuarioFocusLost

    private void loginUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginUsuarioFocusGained
        // TODO add your handling code here:
        if (loginUsuario.getText().equals("Login")) {
            loginUsuario.setText(null);
            loginUsuario.requestFocus();
            PlaceHolder.removePlaceHolder(loginUsuario);
        }
    }//GEN-LAST:event_loginUsuarioFocusGained

    private void loginUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginUsuarioFocusLost
        // TODO add your handling code here:
        if (loginUsuario.getText().isEmpty()) {
            loginUsuario.setText("Login");
            PlaceHolder.addPlaceHolder(loginUsuario);
        }
    }//GEN-LAST:event_loginUsuarioFocusLost

    private void senhaUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_senhaUsuarioFocusGained
        // TODO add your handling code here:
        if (senhaUsuario.getText().equals("Senha")) {
            senhaUsuario.setText(null);
            senhaUsuario.requestFocus();
            PlaceHolder.removePlaceHolder(senhaUsuario);
        }

    }//GEN-LAST:event_senhaUsuarioFocusGained

    private void senhaUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_senhaUsuarioFocusLost
        // TODO add your handling code here:       
        if (senhaUsuario.getText().isEmpty()) {
            senhaUsuario.setText("Senha");
            PlaceHolder.addPlaceHolder(senhaUsuario);
        }
    }//GEN-LAST:event_senhaUsuarioFocusLost

    private void senhaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senhaUsuarioActionPerformed

    private void comboPermissoesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_comboPermissoesFocusGained
        // TODO add your handling code here:
        if (comboPermissoes.getSelectedItem().toString().equals("Selecione a permissão")) {
            comboPermissoes.requestFocus();
            PlaceHolder.removePlaceHolderComboBox(comboPermissoes);
        }
    }//GEN-LAST:event_comboPermissoesFocusGained

    private void comboPermissoesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_comboPermissoesFocusLost
        // TODO add your handling code here:
        if (comboPermissoes.getSelectedItem().toString().equals("Selecione a permissão")) {
            PlaceHolder.addPlaceHolderComboBox(comboPermissoes);
        }
    }//GEN-LAST:event_comboPermissoesFocusLost

    private void CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarActionPerformed
        // TODO add your handling code here:
        DAOOperacoes dao = new DAOOperacoes();
        String nome = nomeUsuario.getText();
        String permissao = comboPermissoes.getSelectedItem().toString();
        String email = emailUsuario.getText();
        String telefone = telefoneUsuario.getText();
        LocalDate data = LocalDate.now();
        LocalTime hora = LocalTime.now();
        String login = loginUsuario.getText();
        
        String senha = dao.getSHA2(dao.getMD5(senhaUsuario.getText()));

        String log = "Início do log de: " + nome + " (" + permissao + ").";

        boolean camposPreenchidos = !nome.equals("Nome") && !email.equals("Email (nome@exemplo.dominio)") && !telefone.equals("Telefone (Exemplo: (27)981026479)") && !login.equals("Login") && !senha.equals("Senha");
        boolean comboBoxSelecionada = !permissao.equals("Selecione a permissão");

        try {
            if (!camposPreenchidos) {
                JOptionPane.showMessageDialog(null, "Todos os campos de dados pessoais devem estar preenchidos.");
            }

            if (!comboBoxSelecionada) {
                JOptionPane.showMessageDialog(null, "Todas as combo boxes devem estar com seleções válidas para que o cadastro ocorra.");
            }

            if (camposPreenchidos && comboBoxSelecionada) {
                User u = new User(nome, permissao, email, telefone, data, hora, login, senha, log);

                dao.cadastrarJPA(u);

                nomeUsuario.setText("Nome");
                PlaceHolder.addPlaceHolder(nomeUsuario);
                comboPermissoes.setSelectedIndex(0);
                PlaceHolder.addPlaceHolderComboBox(comboPermissoes);
                emailUsuario.setText("Email (nome@exemplo.dominio)");
                PlaceHolder.addPlaceHolder(emailUsuario);
                telefoneUsuario.setText("Telefone (Exemplo: (27)981026479)");
                PlaceHolder.addPlaceHolder(telefoneUsuario);
                loginUsuario.setText("Login");
                PlaceHolder.addPlaceHolder(loginUsuario);
                senhaUsuario.setText("Senha");
                PlaceHolder.addPlaceHolder(senhaUsuario);
                JOptionPane.showMessageDialog(null, "Cadastro bem sucedido.");
            }
        } catch (Exception e) {
            System.out.println("Ocorreu um erro, preencha todos os campos e tente novamente!");
            System.out.println(e);
        }
        DAOOperacoes.closeMan();
    }//GEN-LAST:event_CadastrarActionPerformed

    private void visualizacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visualizacaoActionPerformed
        // TODO add your handling code here:
        if (senhaUsuario.getEchoChar() == '\u2022') {
            senhaUsuario.setEchoChar((char) 0);
        } else {
            senhaUsuario.setEchoChar('\u2022');
        }
    }//GEN-LAST:event_visualizacaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CadastroUser().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cadastrar;
    private javax.swing.JComboBox<String> comboPermissoes;
    private javax.swing.JTextField emailUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField loginUsuario;
    private javax.swing.JTextField nomeUsuario;
    private javax.swing.JPasswordField senhaUsuario;
    private javax.swing.JTextField telefoneUsuario;
    private javax.swing.JButton visualizacao;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
