/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.SistemaEscolarDeAutomacao.Gui.Consultas;

import com.mycompany.SistemaEscolarDeAutomacao.Dao.DAOOperacoes;
import com.mycompany.SistemaEscolarDeAutomacao.Entities.User;
import com.mycompany.SistemaEscolarDeAutomacao.Gerais.PlaceHolder;
import com.mycompany.SistemaEscolarDeAutomacao.Gerais.PreencherTabelas;
import java.util.List;

/**
 *
 * @author mrdaniel
 */
public class ConsultasDeUsuario extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ConsultasDeUsuario.class.getName());

    private static ConsultasDeUsuario instance;

    public static ConsultasDeUsuario getInstance() {
        if (instance == null) {
            instance = new ConsultasDeUsuario();
        }
        return instance;
    }

    public static void setInstance(ConsultasDeUsuario instance) {
        ConsultasDeUsuario.instance = instance;
    }

    /**
     * Creates new form ConsultasDeUsuario
     */
    public ConsultasDeUsuario() {
        initComponents();
        PlaceHolder.addPlaceHolder(nomeUsuario);
        PlaceHolder.addPlaceHolderComboBox(permissaoUsuario);
        PlaceHolder.addPlaceHolder(emailUsuario);
        PlaceHolder.addPlaceHolder(telefoneUsuario);
        PlaceHolder.addPlaceHolder(dataCadastro);
        PlaceHolder.addPlaceHolder(horaCadastro);
        
        List<User> lista = DAOOperacoes.buscarTudo();
        PreencherTabelas.PreencherTabelaDeUsuarios(jTable1, lista);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        horaCadastro = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        telefoneUsuario = new javax.swing.JTextField();
        dataCadastro = new javax.swing.JTextField();
        permissaoUsuario = new javax.swing.JComboBox<>();
        nomeUsuario = new javax.swing.JTextField();
        emailUsuario = new javax.swing.JTextField();
        voltar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        horaCadastro.setFont(new java.awt.Font("Noto Sans", 2, 13)); // NOI18N
        horaCadastro.setText("HH:mm:ss (Hora do cadastro)");
        horaCadastro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                horaCadastroFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                horaCadastroFocusLost(evt);
            }
        });
        horaCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horaCadastroActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Noto Sans", 0, 36)); // NOI18N
        jLabel1.setText("Usuários Cadastrados");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setText("Selecione os critérios de busca:");

        telefoneUsuario.setFont(new java.awt.Font("Noto Sans", 2, 13)); // NOI18N
        telefoneUsuario.setText("Telefone");
        telefoneUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                telefoneUsuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                telefoneUsuarioFocusLost(evt);
            }
        });
        telefoneUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefoneUsuarioActionPerformed(evt);
            }
        });

        dataCadastro.setFont(new java.awt.Font("Noto Sans", 2, 13)); // NOI18N
        dataCadastro.setText("--/--/---- (Data de cadastro)");
        dataCadastro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dataCadastroFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                dataCadastroFocusLost(evt);
            }
        });
        dataCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataCadastroActionPerformed(evt);
            }
        });

        permissaoUsuario.setFont(new java.awt.Font("Noto Sans", 2, 13)); // NOI18N
        permissaoUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione a permissão", "Diretor", "Secretário", "Professor" }));
        permissaoUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                permissaoUsuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                permissaoUsuarioFocusLost(evt);
            }
        });

        nomeUsuario.setText("Nome");
        nomeUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nomeUsuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nomeUsuarioFocusLost(evt);
            }
        });
        nomeUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeUsuarioActionPerformed(evt);
            }
        });

        emailUsuario.setFont(new java.awt.Font("Noto Sans", 2, 13)); // NOI18N
        emailUsuario.setText("Email");
        emailUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailUsuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailUsuarioFocusLost(evt);
            }
        });
        emailUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailUsuarioActionPerformed(evt);
            }
        });

        voltar.setText("Voltar");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });

        jButton2.setText("Ver log");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(voltar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(horaCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(permissaoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(telefoneUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(emailUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(100, 100, 100))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(permissaoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(horaCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefoneUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(voltar)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void horaCadastroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_horaCadastroFocusGained
        // TODO add your handling code here:
        if (horaCadastro.getText().equals("HH:mm:ss (Hora do cadastro)")) {
            horaCadastro.setText(null);
            horaCadastro.requestFocus();
            PlaceHolder.removePlaceHolder(horaCadastro);
        }
    }//GEN-LAST:event_horaCadastroFocusGained

    private void horaCadastroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_horaCadastroFocusLost
        // TODO add your handling code here:
        if (horaCadastro.getText().isEmpty()) {
            horaCadastro.setText("HH:mm:ss (Hora do cadastro)");
            PlaceHolder.addPlaceHolder(horaCadastro);
        }
    }//GEN-LAST:event_horaCadastroFocusLost

    private void horaCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horaCadastroActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_horaCadastroActionPerformed

    private void telefoneUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefoneUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefoneUsuarioActionPerformed

    private void dataCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataCadastroActionPerformed

    private void nomeUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeUsuarioActionPerformed

    private void emailUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailUsuarioActionPerformed

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        // TODO add your handling code here:
        dispose();
        ConsultasDeUsuario.setInstance(null);
        Consultas.getInstance().setVisible(true);
    }//GEN-LAST:event_voltarActionPerformed

    private void nomeUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomeUsuarioFocusGained
        // TODO add your handling code here:
        if (nomeUsuario.getText().equals("Nome")) {
            nomeUsuario.setText(null);
            nomeUsuario.requestFocus();
            PlaceHolder.removePlaceHolder(nomeUsuario);
        }
    }//GEN-LAST:event_nomeUsuarioFocusGained

    private void nomeUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomeUsuarioFocusLost
        // TODO add your handling code here:
        if (nomeUsuario.getText().isEmpty()) {
            PlaceHolder.addPlaceHolder(nomeUsuario);
            nomeUsuario.setText("Nome");
        }
    }//GEN-LAST:event_nomeUsuarioFocusLost

    private void permissaoUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_permissaoUsuarioFocusGained
        // TODO add your handling code here:
        if (permissaoUsuario.getSelectedItem().toString().equals("Selecione a permissão")) {
            permissaoUsuario.requestFocus();
            PlaceHolder.removePlaceHolderComboBox(permissaoUsuario);
        }
    }//GEN-LAST:event_permissaoUsuarioFocusGained

    private void permissaoUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_permissaoUsuarioFocusLost
        // TODO add your handling code here:
        if (permissaoUsuario.getSelectedItem().toString().equals("Selecione a permissão")) {
            PlaceHolder.addPlaceHolderComboBox(permissaoUsuario);
        }
    }//GEN-LAST:event_permissaoUsuarioFocusLost

    private void dataCadastroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dataCadastroFocusGained
        // TODO add your handling code here:
        if (dataCadastro.getText().equals("--/--/---- (Data de cadastro)")) {
            dataCadastro.setText(null);
            dataCadastro.requestFocus();
            PlaceHolder.removePlaceHolder(dataCadastro);
        }
    }//GEN-LAST:event_dataCadastroFocusGained

    private void dataCadastroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dataCadastroFocusLost
        // TODO add your handling code here:
         if (dataCadastro.getText().isEmpty()) {
            PlaceHolder.addPlaceHolder(dataCadastro);
            dataCadastro.setText("--/--/---- (Data de cadastro)");
        }
    }//GEN-LAST:event_dataCadastroFocusLost

    private void telefoneUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_telefoneUsuarioFocusGained
        // TODO add your handling code here:
        if (telefoneUsuario.getText().equals("Telefone")) {
            telefoneUsuario.setText(null);
            telefoneUsuario.requestFocus();
            PlaceHolder.removePlaceHolder(telefoneUsuario);
        }
    }//GEN-LAST:event_telefoneUsuarioFocusGained

    private void telefoneUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_telefoneUsuarioFocusLost
        // TODO add your handling code here:
        if (telefoneUsuario.getText().isEmpty()) {
            PlaceHolder.addPlaceHolder(telefoneUsuario);
            telefoneUsuario.setText("Telefone");
        }
    }//GEN-LAST:event_telefoneUsuarioFocusLost

    private void emailUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailUsuarioFocusGained
        // TODO add your handling code here:
        if (emailUsuario.getText().equals("Email")) {
            emailUsuario.setText(null);
            emailUsuario.requestFocus();
            PlaceHolder.removePlaceHolder(emailUsuario);
        }
    }//GEN-LAST:event_emailUsuarioFocusGained

    private void emailUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailUsuarioFocusLost
        // TODO add your handling code here:
         if (emailUsuario.getText().isEmpty()) {
            PlaceHolder.addPlaceHolder(emailUsuario);
            emailUsuario.setText("Email");
        }
    }//GEN-LAST:event_emailUsuarioFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ConsultasDeUsuario().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dataCadastro;
    private javax.swing.JTextField emailUsuario;
    private javax.swing.JTextField horaCadastro;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField nomeUsuario;
    private javax.swing.JComboBox<String> permissaoUsuario;
    private javax.swing.JTextField telefoneUsuario;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
